---
Name: imagecropfield
After:
  - "assetsimage"
---
SilverStripe\AssetAdmin\Forms\ImageFormFactory:
  extensions:
    - Seppzzz\ImageCropField\Extensions\ImageCropFieldAssetFormFactoryExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "seppzzz/silverstripe-image-cropper-field: css/cropper.min.css"
    - "seppzzz/silverstripe-image-cropper-field: css/imagescropfield.css"
  extra_requirements_javascript:
    - "seppzzz/silverstripe-image-cropper-field: javascript/boot/boot.js"